@startuml
'https://plantuml.com/use-case-diagram

:TrafficManager: as TM
(Knows the most efficiency circuit given a source location) as (Circuit)

TM -> (Circuit)

note left of TM : This an TrafficManager.

@enduml